[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0
tokenKey = "ms_token:"
MaxIdel = 100
MaxActive = 4000
IdleTimeout = 180
[pg]
host = "127.0.0.1"
port = 5432
user = "raohao"
password = "123456"
db = "ms"
MaxOpenConns = 1000
MaxIdleConns = 100
[jwt]
key = "nlkKX87"
